### ISSUE TITLE
Use Properties file instead of hard coded links

### ISSUE THREAD

**Issue by hilpold** [miamidade/open311#2]
Hi Camilo,

create 2 properties files, one for test, one for production.
These should contain all needed links and the code should be modified to use them.

**Comment by sabbas** [comment]
In the portal password reset project on git there is a config bean i created which autowires properties to values set in the application.properties file. You can use this as a guide.

-------- Original message --------
From: Thomas Hilpold
Date:05/18/2015 12:04 PM (GMT-05:00)
To: miamidade/open311
Subject: [open311] Use Properties file instead of hard coded links (#2)


Hi Camillo,

create 2 properties files, one for test, one for production.
These should contain all needed links and the code should be modified to use them.

**Comment by kamellcuba** [comment]
Done. Changes discussed with Thomas.

**Comment by hilpold** [comment]
The changes tie our open311 implementation to Spring for good, while before most of it, except for the very top layer would have been useful in a variety of environments (J2EE, JBoss, standalone, et.c.).
